name: vrprofile
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.10.14
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - astunparse==1.6.3
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - filelock==3.16.0
    - flatbuffers==24.3.25
    - fonttools==4.53.1
    - fsspec==2024.9.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.66.1
    - h5py==3.11.0
    - idna==3.8
    - jinja2==3.1.4
    - joblib==1.4.2
    - keras==3.5.0
    - kiwisolver==1.4.7
    - libclang==18.1.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - mdurl==0.1.2
    - ml-dtypes==0.4.0
    - mpmath==1.3.0
    - namex==0.0.8
    - networkx==3.3
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.68
    - nvidia-nvtx-cu12==12.1.105
    - opt-einsum==3.3.0
    - optree==0.12.1
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - pip==24.2
    - protobuf==4.25.4
    - pygments==2.18.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - requests==2.32.3
    - rich==13.8.0
    - scikit-learn==1.5.1
    - scipy==1.14.1
    - seaborn==0.13.2
    - setuptools==72.1.0
    - six==1.16.0
    - sympy==1.13.2
    - tensorboard==2.17.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.17.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - torch==2.4.1
    - torchvision==0.19.1
    - triton==3.0.0
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - werkzeug==3.0.4
    - wheel==0.43.0
    - wrapt==1.16.0
    - xgboost==2.1.1

